### ISSUE TITLE
Add Python syntax highlighting to the text editor

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#7]
This is one of the more advanced and important issues to tackle.

**Comment by Ryuno-Ki** [comment]
I think, [Pygments](https://pypi.org/project/Pygments/) would be the way to go here.

There are [resources on StackOverflow](https://stackoverflow.com/q/29688831) or [other projects on GitHub](https://github.com/JamesStallings/pyro/blob/bde0bd6d31d94b0fe4cf07f682ee11cafe2be8b5/pyro) which could be used to get some ideas on how to get started.

**Comment by SethWalkeroo** [comment]
@Ryuno-Ki I've mulled over stack overflow a bit. I will check out Pygments. Thank you for the resources!

**Comment by WhiteHeadbanger** [comment]
Hi! I would like to contribute on this. It would be my first contribution ever

**Comment by SethWalkeroo** [comment]
@WhiteHeadbanger You can contribute to the project, but i'm not really sure how I want to tackle this specific issue yet. If you have something you want to improve on or fix, you can create an issue, and then make a pull request accordingly.

**Comment by WhiteHeadbanger** [comment]
Fair enough. I'll be using the software for a bit to get familiarized with it

**Comment by Sounakde** [comment]
What do I have to do to use this software?

**Comment by WhiteHeadbanger** [comment]
> What do I have to do to use this software?

Just clone it and run the quiet.py file

**Comment by Ryuno-Ki** [comment]
In case `python3 -m tkinter` throws an error, you can [use Docker for it](https://github.com/SethWalkeroo/Quiet-Text#installation) (assuming a GNU/Linux system).

If you can use tkinter, I'd suggest to set up a virtual environment (I'm still using `virtualenv --python=python3` from my Python2.7 days …), activate it and then execute `python -m quiet.py` within that.

@SethWalkeroo Since @Sounakde asked and @WhiteHeadbanger reported to be a first-time contributor, it might make sense to extend the README for a local setup. Let me create a separate issue for that!

**Comment by SethWalkeroo** [comment]
@Ryuno-Ki Sounds great!
